spring:
  application:
    name: roomManagementService

  
  datasource:   
    url: jdbc:mysql://localhost:3306/hms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asdkf

  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  
  
 
server:
  port: 8082