spring:
  application:
    name: roomManagementService

  
  datasource:   
    url: jdbc:h2:mem:hmsdb
    driver-class-name: org.h2.Driver
    username: Admin
    password: 123

  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  
  h2:
    console:
      enabled: true
      path: /h2-console
 
server:
  port: 8082